baseURL = "https://zccc.blog"
locale = "zh-CN"
title = "zccc"
theme = "stack"
paginate = 10

[params]
  description = "小祝的个人博客"
  author = "小祝"

  # 灰色简约
  mainSections = ["posts"]
  [params.dateFormat]
    published = "2006-01-02"
    lastUpdated = "2006-01-02"
  [params.colorScheme]
    toggle = true
    default = "auto"

  # 主页
  [params.home]
    enableRecentPosts = true
    recentPostCount = 5

  # 侧边栏
  [params.sidebar]
    compact = true
    subtitle = "记录一些想法和日常"


  # 页脚
  [params.footer]
    since = 2025
    customText = ""

  # 文章
  [params.article]
    Math = false
    toc = true
    readingTime = true
    license = { enabled = false }
    breadcrumb = false

  # 评论
  [params.comments]
    enabled = false

  # 小部件
  [params.widgets]
    enabled = ["tagCloud"]

[params.widgets.tagCloud]
  enabled = true
  max = 10

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/p/"
    weight = 4

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]
